---
name: AmneziaWG
version: dev
slug: wireguard
description: WireGuard-Go fork with protection against DPI systems.
url: https://github.com/yury-sannikov/addon-amnezia-wireguard
codenotary: codenotary@frenck.dev
arch:
  - aarch64
  - amd64
  - armv7
init: false
ports:
  80/tcp: null
  51820/udp: 51820
ports_description:
  80/tcp: WireGuard peers status API
  51820/udp: "WireGuard: forward this port in your router"
hassio_api: true
privileged:
  - NET_ADMIN
devices:
  - /dev/net/tun
map:
  - ssl:rw
options:
  server:
    host: myautomatedhome.duckdns.org
    addresses:
      - 172.27.66.1
    dns: []
  peers:
    - name: hassio
      addresses:
        - 172.27.66.2
      allowed_ips: []
      client_allowed_ips: []
      ping_address: 172.27.66.2
  amnezia:
    junk_packet_count: 3
    junk_packet_min_size: 100
    junk_packet_max_size: 1000
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  server:
    host: str
    interface: match(^wg([0-9])+$)?
    addresses:
      - str
    dns:
      - str
    private_key: password?
    public_key: str?
    fwmark: str?
    table: str?
    pre_up: str?
    pre_down: str?
    post_up: str?
    post_down: str?
    mtu: int?
  peers:
    - name: match(^[a-zA-Z0-9\d](?:[a-zA-Z0-9\d]|-(?=[a-zA-Z0-9\d])){0,32}$)
      private_key: str?
      public_key: str?
      addresses:
        - str
      allowed_ips:
        - str
      client_allowed_ips:
        - str
      persistent_keep_alive: int?
      endpoint: str?
      pre_shared_key: str?
      fwmark: str?
      ping_address: str?
  amnezia:
    junk_packet_count: int
    junk_packet_min_size: int
    junk_packet_max_size: int
    init_packet_junk_size: int?
    response_packet_junk_size: int?
    init_packet_magic_header: int?
    response_packet_magic_header: int?
    transport_packet_magic_header: int?
    uload_packet_magic_header: int?


